apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: article-service               # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: article-service               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations-news
          image: antohachaban/article-service-migrations:latest 
          command: ["migrate", "-path", "/migrations", "-database", "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://admin:admin@postgres:5432/mnews_articles?sslmode=disable"
            - name: VERSION
              value: "000001"
      containers:
        - image: antohachaban/article-service:latest       # образ Docker
          imagePullPolicy: IfNotPresent  
          name: article-service           # ім'я контейнеру
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: article-service-config
            - secretRef:
                name: article-service-secret  