apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate-deploy
  labels:
    type: libretranslate
spec:
  selector: 
    matchLabels:
      app: libretranslate
  replicas: 1
  template:
    metadata:
      name: libretranslate
      labels:
        app: libretranslate
    spec:
      containers:
        - name: antohachaban-libretranslate
          image: antohachaban/libretranslate:latest
          ports:
            - containerPort: 5000
