# apiVersion: v1
# kind: Service
# metadata:
#   name: translate-service-service
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80         # порт по якому можна звератись до сервісу
#       targetPort: 5000 # порт контейнера
#       # nodePort: 32002 # порт на якому буде доступний сервіс ззовні
#   selector:
#     app: translate-service
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: translate-service
# spec:
#   selector:
#     app: libretranslate
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 5000

# apiVersion: v1
# kind: Service
# metadata:
#   name: libretranslate
# spec:
#   selector:
#     app: libretranslate
#   ports:
#     - port: 80
#       targetPort: 5000
#   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: libretranslate-svc
spec:
  type: LoadBalancer
  selector:
    app: libretranslate
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
