apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: parsing-service               # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: parsing-service               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: antohachaban/parsing-service-local:latest       # образ Docker
          imagePullPolicy: IfNotPresent  
          name: parsing-service           # ім'я контейнеру
          ports:
            - containerPort: 8080  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: parsing-service-config
            - secretRef:
                name: parsing-service-secret  