apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service-deployment
spec:
  replicas: 1                      
  selector:
    matchLabels:
      app: article-service               
  template:
    metadata:
      labels:
        app: article-service               
    spec:
      initContainers:
        - name: run-migrations-news
          image: antohachaban/article-service-migrations:latest 
          command: ["migrate", "-path", "/migrations", "-database", "$(POSTGRESQL_URL)", "goto", "$(VERSION)"]
          env:
            - name: POSTGRESQL_URL
              value: "postgres://admin:admin@postgres:5432/mnews_articles?sslmode=disable"
            - name: VERSION
              value: "000001"
      containers:
        - image: antohachaban/article-service:latest       
          imagePullPolicy: IfNotPresent  
          name: article-service           
          ports:
            - containerPort: 8080 
          envFrom:
            - configMapRef:
                name: article-service-config
            - secretRef:
                name: article-service-secret  