apiVersion: v1
kind: Service
metadata:
  name: article-service-service
spec:
  type: ClusterIP
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 8080 # порт контейнера
  selector:
    app: article-service