apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: user-service-secret

data:
  POSTGRES_USER: "YWRtaW4=" # admin
  POSTGRES_PASSWORD: "YWRtaW4=" # admin
  RABBITMQ_USER: "Z3Vlc3Q=" #guest
  RABBITMQ_PASSWORD: "Z3Vlc3Q=" #guest