apiVersion: v1
kind: Service
metadata:
  name: category-service-service
spec:
  type: ClusterIP #LoadBalancer #ClusterIP #
  ports:
    #- protocol: "TCP"
    - port: 5001
      targetPort: 5000
  selector:
    app: category-service