apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: antohachaban/clientv2-service:latest
          ports:
            - containerPort: 80
