apiVersion: v1
kind: Service
metadata:
  name: client-service-service
spec:
  type: ClusterIP
  ports:
    - port: 80         # порт по якому можна звератись до сервісу
      targetPort: 80 # порт контейнера
      # nodePort: 32002 # порт на якому буде доступний сервіс ззовні
  selector:
    app: client-service