apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  persistence:
    storageClassName: standard
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbimq-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /mnt/app/rabbitmq
    type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-service
# spec:
#   selector:
#     app: rabbitmq
#   ports:
#     - protocol: TCP
#       port: 5672
#       targetPort: 5672
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-management
# spec:
#   selector:
#     app: rabbitmq
#   ports:
#     - protocol: TCP
#       port: 15672
#       targetPort: 15672